Fixed a double assignment
anchore/enterprise-client-go pull request #3
Opened 2021-04-19 20:46 UTC by Toure

Corrected a autogenerated code issue where a local variable
was generated twice within the same scope.

Signed-off-by: Toure Dunnon <toure.dunnon@anchore.com>

2021-04-19 21:53 UTC, dakaneye requested changes
Unfortunately this doesn't seem like a good long term solution as any subsequent codegen executions will overwrite this...we need to figure out a better way to fix the issue in the codegen client:
* either we can edit the swagger spec to make it work OR
* need to make a change to fix the bug in the codegen code itself (which is it fails to generate good code when a request body has two file parameters)

2021-04-20 17:37 UTC, rbrady approved these changes

2021-04-20 18:01 UTC, Toure commented
> Unfortunately this doesn't seem like a good long term solution as any subsequent codegen executions will overwrite this...we need to figure out a better way to fix the issue in the codegen client:
> 
> * either we can edit the swagger spec to make it work OR
> * need to make a change to fix the bug in the codegen code itself (which is it fails to generate good code when a request body has two file parameters)

@dakaneye issues addressed.

2021-04-20 18:08 UTC, dakaneye approved these changes

2021-04-21 14:33 UTC, Vijay-P approved these changes

2021-04-21 14:39 UTC, merged